// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnCI4ad8LSHAPC-Fd3cX5tNieGuHK3_Ik',
    appId: '1:481287089723:web:56ac469d1ae253160ab61e',
    messagingSenderId: '481287089723',
    projectId: 'my-panaderia-proyect',
    authDomain: 'my-panaderia-proyect.firebaseapp.com',
    storageBucket: 'my-panaderia-proyect.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz_ecqDKoewOGCClUmS1fKNi9qHz0ik4Y',
    appId: '1:481287089723:android:a719a3a663f9cdf10ab61e',
    messagingSenderId: '481287089723',
    projectId: 'my-panaderia-proyect',
    storageBucket: 'my-panaderia-proyect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1Th51O1yy8qnOTfLE31eO8Uuw3h4DtGc',
    appId: '1:481287089723:ios:912a9dae3455548b0ab61e',
    messagingSenderId: '481287089723',
    projectId: 'my-panaderia-proyect',
    storageBucket: 'my-panaderia-proyect.firebasestorage.app',
    iosBundleId: 'com.example.panaderiaDelicia',
  );
}
